const actions = {
  ADD_EMPLOYMENT: 'ADD_EMPLOYMENT',
  UPDATE_EMPLOYMENT: 'UPDATE_EMPLOYMENT',
  REMOVE_EMPLOYMENT: 'REMOVE_EMPLOYMENT',

  ADD_EDUCATION: 'ADD_EDUCATION',
  UPDATE_EDUCATION: 'UPDATE_EDUCATION',
  REMOVE_EDUCATION: 'REMOVE_EDUCATION',

  ADD_SKILL: 'ADD_SKILL',
  UPDATE_SKILL: 'UPDATE_SKILL',
  REMOVE_SKILL: 'REMOVE_SKILL',

  ADD_LINK: 'ADD_LINK',
  UPDATE_LINK: 'UPDATE_LINK',
  REMOVE_LINK: 'REMOVE_LINK',

  ADD_LANGUAGE: 'ADD_LANGUAGE',
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  REMOVE_LANGUAGE: 'REMOVE_LANGUAGE',

  UPDATE_PERSONAL_DETAILS: 'UPDATE_PERSONAL_DETAILS',
  UPDATE_ANONYMOUS_LOGIN: 'UPDATE_ANONYMOUS_LOGIN',
  UPDATE_TEMPLATE_VALUES: 'UPDATE_TEMPLATE_VALUES',
  UPDATE_KEEPDATA: 'UPDATE_KEEPDATA'
}
export default actions
