const actions = {
  ADD_EMPLOYMENT: "ADD_EMPLOYMENT",
  ADD_EDUCATION: "ADD_EDUCATION",
  ADD_SKILL: "ADD_SKILL",
  ADD_LINK: "ADD_LINK",
  ADD_LANGUAGE: "ADD_LANGUAGE",
  REMOVE_EMPLOYMENT: "REMOVE_EMPLOYMENT",
  REMOVE_EDUCATION: "REMOVE_EDUCATION",
  REMOVE_SKILL: "REMOVE_SKILL",
  REMOVE_LINK: "REMOVE_LINK",
  REMOVE_LANGUAGE: "REMOVE_LANGUAGE",
  UPDATE_PERSONAL_DETAILS: "UPDATE_PERSONAL_DETAILS",
  UPDATE_EMPLOYMENT: "UPDATE_EMPLOYMENT",
  UPDATE_EDUCATION: "UPDATE_EDUCATION",
  UPDATE_SKILL: "UPDATE_SKILL",
  UPDATE_LINK: "UPDATE_LINK",
  UPDATE_LANGUAGE: "UPDATE_LANGUAGE",
  UPDATE_TEMPLATE_VALUES: "UPDATE_TEMPLATE_VALUES",
  UPDATE_PREVIEW_MODE: "UPDATE_PREVIEW_MODE",

};
export default actions;
